# Docker Compose YAML file for lighttpd

# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

# after start, enter shell with:
# $ sudo docker exec -it lighttpddocker_lighttpd_1 ash
version: '3'
services:
    lighttpd:
        image: ghcr.io/forinil/lighttpd:latest
        build: .
        restart: always
        ports:
            - "8001:80" # for testing purposes, (un)comment as required
        #tty: true
